# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22cf7f8e9131174f420581aa792a8e01"
application_url = "https://upgrading-measured-prostate-crack.trycloudflare.com"
embedded = true
name = "checkout-extensibility"
handle = "checkout-extensibility-75"

[build]
include_config_on_deploy = true
dev_store_url = "theme456.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://upgrading-measured-prostate-crack.trycloudflare.com/auth/callback",
  "https://upgrading-measured-prostate-crack.trycloudflare.com/auth/shopify/callback",
  "https://upgrading-measured-prostate-crack.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
